version: '3.8'

services:
  # Database Service: PostgreSQL with TimescaleDB
  zabbix-db:
    image: docker.io/timescale/timescaledb:latest-pg16
    container_name: kr-netmon-zabbix-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${KR_NETMON_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - kr-netmon-db-data:/var/lib/postgresql/data:rw
      - ./zbx_env/usr/var/lib/postgresql/data:/var/lib/postgresql/data_dump:rw
    networks:
      - kr-netmon-backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 1G

  # Zabbix Server
  zabbix-server:
    image: docker.io/zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: kr-netmon-zabbix-server
    restart: unless-stopped
    ports:
      - "10051:10051"
    volumes:
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
    environment:
      - DB_SERVER_HOST=zabbix-db
      - DB_SERVER_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${KR_NETMON_DB_PASSWORD}
      - ZBX_CACHESIZE=512M
      - ZBX_HISTORYCACHESIZE=128M
      - ZBX_TRENDCACHESIZE=128M
      - ZBX_HISTORYINDEXCACHESIZE=128M
      - ZBX_VALUECACHESIZE=256M
    networks:
      - kr-netmon-backend
      - kr-netmon-frontend
    depends_on:
      zabbix-db:
        condition: service_healthy
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Zabbix Web Interface (Nginx)
  zabbix-web-nginx-pgsql:
    image: docker.io/zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: kr-netmon-zabbix-web
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "8443:8443"
    volumes:
      - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ./zbx_env/usr/share/zabbix/modules:/usr/share/zabbix/modules:ro
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-db
      - DB_SERVER_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${KR_NETMON_DB_PASSWORD}
      - PHP_TZ=Asia/Seoul
    networks:
      - kr-netmon-backend
      - kr-netmon-frontend
    depends_on:
      - zabbix-server

  # SNMP Trap Handling
  zabbix-snmptraps:
    image: docker.io/zabbix/zabbix-snmptraps:alpine-7.0-latest
    container_name: kr-netmon-zabbix-snmptraps
    restart: unless-stopped
    ports:
      - "1162:1162/udp"
    volumes:
      - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
    networks:
      - kr-netmon-frontend
    depends_on:
      - zabbix-server

  # Grafana for Visualization
  grafana:
    image: docker.io/grafana/grafana-enterprise:latest
    container_name: kr-netmon-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${KR_NETMON_GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/
    volumes:
      - ./grafana_data:/var/lib/grafana:rw
      - ./grafana/provisioning:/etc/grafana/provisioning:rw
    networks:
      - kr-netmon-frontend
    depends_on:
      zabbix-db:
        condition: service_healthy
      zabbix-web-nginx-pgsql:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M

  # Optional: Prometheus and SNMP Exporter
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: kr-netmon-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - kr-netmon-backend

  snmp-exporter:
    image: docker.io/prom/snmp-exporter:latest
    container_name: kr-netmon-snmp-exporter
    restart: unless-stopped
    ports:
      - "9116:9116"
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml:ro
    networks:
      - kr-netmon-backend

networks:
  kr-netmon-frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  kr-netmon-backend:
    driver: bridge
    internal: true

volumes:
  kr-netmon-db-data:
